name: Deploy

on:

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  upstream-deploy:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setting up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validating Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b


      - name: Building JAR with Gradle
        run: |
          chmod +x gradlew
          ./gradlew bootJar
          mv build/libs/* build/libs/menu-api.jar

      - name: Setting up SSH
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Terminating running API
        continue-on-error: true
        run: |
          ssh menu@${{ secrets.IP }} "screen -S api -X stuff ^C"
          sleep 3
          ssh menu@${{ secrets.IP }} "screen -XS api quit"

      - name: Transferring built JAR
        run: scp build/libs/menu-api.jar menu@${{ secrets.IP }}:/home/menu/api/menu-api.jar

      - name: Starting new API
        run: ssh menu@${{ secrets.IP }} "screen -S api -dm bash -c 'cd api; java -jar menu-api.jar; exec bash'"
